# See https://ezcv.readthedocs.io for documentation
name: Victor Dong
theme: dimension
resume: false
biography: I am a recent graduate of Computer Science at the University of Calgary. I have gained an interest in cybersecurity and software development while at school. Within my education, I have gained skills in various technologies, which include C++, Java, Python, HTML/CSS and Javascript. # This field is for writing about yourself you can add a > to span multiple lines
examples: true
